## Student Attendance Analytics with Pandas

In [1]:
import pandas as pd
import numpy as np

#### Section 0: Data Loading

In [2]:
df = pd.read_excel("D:/csec/numpy/Pandas/Project1_Student Attendence analytics with Pandas/csec_attendance.xlsx")
df

,Roll No,Student Name,Subject,Total Classes,Present,Absent,Excused,Attendance %,Status,Classes Needed (75%),Last Present Date,Consecutive Absences
0,4MW24CS123,SAKSHI SHETTY,Data Science & GenAI - 3nd Yr - CSE - C,12,12,0,0,100%,Safe,✓ Met,2026-10-09,0
1,4MW24CS124,SAMEEKSHA BEKAL,Data Science & GenAI - 3nd Yr - CSE - C,12,11,1,0,92%,Safe,✓ Met,2026-10-07,1
2,4MW24CS125,SAMEER ACHARYA,Data Science & GenAI - 3nd Yr - CSE - C,12,2,10,0,17%,Critical,28 more,2026-09-25,3
3,4MW24CS126,SAMHITA S RAO,Data Science & GenAI - 3nd Yr - CSE - C,12,9,3,0,75%,Warning,✓ Met,2026-10-09,0
4,4MW24CS127,SAMIKSHA,Data Science & GenAI - 3nd Yr - CSE - C,12,10,2,0,83%,Warning,✓ Met,2026-10-07,1
...,...,...,...,...,...,...,...,...,...,...,...,...
60,4MW24CS900,RIYA SHETTY,Data Science & GenAI - 3nd Yr - CSE - C,12,7,5,0,58%,Critical,8 more,2026-10-09,0
61,4MW25CS401,ANIRUDH,Data Science & GenAI - 3nd Yr - CSE - C,12,8,4,0,67%,Critical,4 more,2026-10-07,1
62,4MW25CS407,SANATH S DEVADIGA,Data Science & GenAI - 3nd Yr - CSE - C,12,1,11,0,8%,Critical,32 more,2026-09-04,10
63,4MW25CS408,SUSHANTH,Data Science & GenAI - 3nd Yr - CSE - C,12,1,11,0,8%,Critical,32 more,2026-09-04,10
64,4MW25CS409,YASHVITH,Data Science & GenAI - 3nd Yr - CSE - C,12,0,12,0,0%,Critical,36 more,Never,12

#### Section 1: Data Inspection

In [3]:
"""Q1. Display the first 10 rows, the shape of the DataFrame, and the data types of each column."""
#-----------------------------Write Solution Code-----------------------------
df.head(10)
df.shape
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 65 entries, 0 to 64
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Roll No               65 non-null     str
 1   Student Name          65 non-null     str
 2   Subject               65 non-null     str
 3   Total Classes         65 non-null     int64
 4   Present               65 non-null     int64
 5   Absent                65 non-null     int64
 6   Excused               65 non-null     int64
 7   Attendance %          65 non-null     str
 8   Status                65 non-null     str
 9   Classes Needed (75%)  65 non-null     str
 10  Last Present Date     65 non-null     str
 11  Consecutive Absences  65 non-null     int64
dtypes: int64(5), str(7)
memory usage: 6.2 KB

In [4]:
"""Q2. Check for missing values in each column. Identify which columns have null values (especially Last Present Date with "Never") and report the count. """
#-----------------------------Write Solution Code-----------------------------
df.eq('Never').sum()

Roll No                 0
Student Name            0
Subject                 0
Total Classes           0
Present                 0
Absent                  0
Excused                 0
Attendance %            0
Status                  0
Classes Needed (75%)    0
Last Present Date       3
Consecutive Absences    0
dtype: int64

In [5]:
"""Q3. Rename the columns to snake_case (e.g., Roll No → roll_no, Student Name → student_name, Attendance % → attendance_pct). Display the updated column list."""
#-----------------------------Write Solution Code-----------------------------
df.columns=df.columns.str.strip().str.lower().str.replace(' ','_').str.replace('%','pct').str.replace('(','').str.replace(')','')
df

,roll_no,student_name,subject,total_classes,present,absent,excused,attendance_pct,status,classes_needed_75pct,last_present_date,consecutive_absences
0,4MW24CS123,SAKSHI SHETTY,Data Science & GenAI - 3nd Yr - CSE - C,12,12,0,0,100%,Safe,✓ Met,2026-10-09,0
1,4MW24CS124,SAMEEKSHA BEKAL,Data Science & GenAI - 3nd Yr - CSE - C,12,11,1,0,92%,Safe,✓ Met,2026-10-07,1
2,4MW24CS125,SAMEER ACHARYA,Data Science & GenAI - 3nd Yr - CSE - C,12,2,10,0,17%,Critical,28 more,2026-09-25,3
3,4MW24CS126,SAMHITA S RAO,Data Science & GenAI - 3nd Yr - CSE - C,12,9,3,0,75%,Warning,✓ Met,2026-10-09,0
4,4MW24CS127,SAMIKSHA,Data Science & GenAI - 3nd Yr - CSE - C,12,10,2,0,83%,Warning,✓ Met,2026-10-07,1
...,...,...,...,...,...,...,...,...,...,...,...,...
60,4MW24CS900,RIYA SHETTY,Data Science & GenAI - 3nd Yr - CSE - C,12,7,5,0,58%,Critical,8 more,2026-10-09,0
61,4MW25CS401,ANIRUDH,Data Science & GenAI - 3nd Yr - CSE - C,12,8,4,0,67%,Critical,4 more,2026-10-07,1
62,4MW25CS407,SANATH S DEVADIGA,Data Science & GenAI - 3nd Yr - CSE - C,12,1,11,0,8%,Critical,32 more,2026-09-04,10
63,4MW25CS408,SUSHANTH,Data Science & GenAI - 3nd Yr - CSE - C,12,1,11,0,8%,Critical,32 more,2026-09-04,10
64,4MW25CS409,YASHVITH,Data Science & GenAI - 3nd Yr - CSE - C,12,0,12,0,0%,Critical,36 more,Never,12

In [6]:
"""Q4. Convert Attendance % from string format (e.g., "64%") to a numeric float column (0.64 or 64.0). Also convert Last Present Date to datetime, handling "Never" as NaT."""
#-----------------------------Write Solution Code-----------------------------
df['attendance_pct']=df['attendance_pct'].str.rstrip('%').astype(float)/100.0
df['last_present_date']=pd.to_datetime(df['last_present_date'].replace('Never',pd.NaT),errors='coerce')
df

,roll_no,student_name,subject,total_classes,present,absent,excused,attendance_pct,status,classes_needed_75pct,last_present_date,consecutive_absences
0,4MW24CS123,SAKSHI SHETTY,Data Science & GenAI - 3nd Yr - CSE - C,12,12,0,0,1.00,Safe,✓ Met,2026-10-09,0
1,4MW24CS124,SAMEEKSHA BEKAL,Data Science & GenAI - 3nd Yr - CSE - C,12,11,1,0,0.92,Safe,✓ Met,2026-10-07,1
2,4MW24CS125,SAMEER ACHARYA,Data Science & GenAI - 3nd Yr - CSE - C,12,2,10,0,0.17,Critical,28 more,2026-09-25,3
3,4MW24CS126,SAMHITA S RAO,Data Science & GenAI - 3nd Yr - CSE - C,12,9,3,0,0.75,Warning,✓ Met,2026-10-09,0
4,4MW24CS127,SAMIKSHA,Data Science & GenAI - 3nd Yr - CSE - C,12,10,2,0,0.83,Warning,✓ Met,2026-10-07,1
...,...,...,...,...,...,...,...,...,...,...,...,...
60,4MW24CS900,RIYA SHETTY,Data Science & GenAI - 3nd Yr - CSE - C,12,7,5,0,0.58,Critical,8 more,2026-10-09,0
61,4MW25CS401,ANIRUDH,Data Science & GenAI - 3nd Yr - CSE - C,12,8,4,0,0.67,Critical,4 more,2026-10-07,1
62,4MW25CS407,SANATH S DEVADIGA,Data Science & GenAI - 3nd Yr - CSE - C,12,1,11,0,0.08,Critical,32 more,2026-09-04,10
63,4MW25CS408,SUSHANTH,Data Science & GenAI - 3nd Yr - CSE - C,12,1,11,0,0.08,Critical,32 more,2026-09-04,10
64,4MW25CS409,YASHVITH,Data Science & GenAI - 3nd Yr - CSE - C,12,0,12,0,0.00,Critical,36 more,NaT,12

#### Section 2: Filtering & Selection

In [10]:
"""Q5. Filter and display all students whose Status is "Critical". Sort them by Attendance % in ascending order."""
#-----------------------------Write Solution Code-----------------------------
critical_students=df[df['status']=='Critical'].sort_values(by='attendance_pct',ascending=True)
display(critical_students)

,roll_no,student_name,subject,total_classes,present,absent,excused,attendance_pct,status,classes_needed_75pct,last_present_date,consecutive_absences
20,4MW24CS144,SHREEHARI SHENOY R,Data Science & GenAI - 3nd Yr - CSE - C,12,0,12,0,0.00,Critical,36 more,NaT,12
43,4MW24CS167,SURAJ R,Data Science & GenAI - 3nd Yr - CSE - C,12,0,12,0,0.00,Critical,36 more,NaT,12
64,4MW25CS409,YASHVITH,Data Science & GenAI - 3nd Yr - CSE - C,12,0,12,0,0.00,Critical,36 more,NaT,12
45,4MW24CS169,SUSHAN S POOJARY,Data Science & GenAI - 3nd Yr - CSE - C,12,1,11,0,0.08,Critical,32 more,2026-09-04,10
63,4MW25CS408,SUSHANTH,Data Science & GenAI - 3nd Yr - CSE - C,12,1,11,0,0.08,Critical,32 more,2026-09-04,10
62,4MW25CS407,SANATH S DEVADIGA,Data Science & GenAI - 3nd Yr - CSE - C,12,1,11,0,0.08,Critical,32 more,2026-09-04,10
53,4MW24CS177,UTHSAV N SHETTY,Data Science & GenAI - 3nd Yr - CSE - C,12,2,10,0,0.17,Critical,28 more,2026-09-09,9
2,4MW24CS125,SAMEER ACHARYA,Data Science & GenAI - 3nd Yr - CSE - C,12,2,10,0,0.17,Critical,28 more,2026-09-25,3
9,4MW24CS133,SARGAM,Data Science & GenAI - 3nd Yr - CSE - C,12,3,9,0,0.25,Critical,24 more,2026-09-25,3
22,4MW24CS146,SHREESHESHA G A,Data Science & GenAI - 3nd Yr - CSE - C,12,4,8,0,0.33,Critical,20 more,2026-10-07,1
41,4MW24CS165,SUNIL BHAT,Data Science & GenAI - 3nd Yr - CSE - C,11,5,6,0,0.45,Critical,13 more,2026-10-07,1
15,4MW24CS139,SHLOAG MAHESH BANT,Data Science & GenAI - 3nd Yr - CSE - C,12,6,6,0,0.50,Critical,12 more,2026-10-07,1
60,4MW24CS900,RIYA SHETTY,Data Science & GenAI - 3nd Yr - CSE - C,12,7,5,0,0.58,Critical,8 more,2026-10-09,0
30,4MW24CS154,SHREYAS SATISH BHAT,Data Science & GenAI - 3nd Yr - CSE - C,12,8,4,0,0.67,Critical,4 more,2026-10-09,0
11,4MW24CS135,SATHWIK G KAMATH,Data Science & GenAI - 3nd Yr - CSE - C,12,8,4,0,0.67,Critical,4 more,2026-10-07,1
17,4MW24CS141,SHRAVAN,Data Science & GenAI - 3nd Yr - CSE - C,12,8,4,0,0.67,Critical,4 more,2026-10-07,1
58,4MW24CS182,VISHNU PRASAD,Data Science & GenAI - 3nd Yr - CSE - C,12,8,4,0,0.67,Critical,4 more,2026-10-09,0
51,4MW24CS175,THEJAS B K,Data Science & GenAI - 3nd Yr - CSE - C,12,8,4,0,0.67,Critical,4 more,2026-09-25,3
46,4MW24CS170,SUSHANTH (SEETHARAMA ACHAR),Data Science & GenAI - 3nd Yr - CSE - C,12,8,4,0,0.67,Critical,4 more,2026-10-09,0
34,4MW24CS158,SINDHU,Data Science & GenAI - 3nd Yr - CSE - C,12,8,4,0,0.67,Critical,4 more,2026-10-09,0
61,4MW25CS401,ANIRUDH,Data Science & GenAI - 3nd Yr - CSE - C,12,8,4,0,0.67,Critical,4 more,2026-10-07,1

In [12]:
"""Q6. Extract all students who have 0 present days (fully absent). List their roll numbers, names, and consecutive absences."""
#-----------------------------Write Solution Code-----------------------------
df[df['present']==0][['roll_no','student_name','consecutive_absences']]

       roll_no        student_name  consecutive_absences
20  4MW24CS144  SHREEHARI SHENOY R                    12
43  4MW24CS167             SURAJ R                    12
64  4MW25CS409            YASHVITH                    12

In [15]:
"""Q7. Using .loc and .iloc, display:
(a) All "Safe" students using .loc
(b) The first 15 rows and columns 2-6 using .iloc """
#-----------------------------Write Solution Code-----------------------------
df.loc[df['status']=='Safe']
df.iloc[:15,2:7]

,subject,total_classes,present,absent,excused
0,Data Science & GenAI - 3nd Yr - CSE - C,12,12,0,0
1,Data Science & GenAI - 3nd Yr - CSE - C,12,11,1,0
2,Data Science & GenAI - 3nd Yr - CSE - C,12,2,10,0
3,Data Science & GenAI - 3nd Yr - CSE - C,12,9,3,0
4,Data Science & GenAI - 3nd Yr - CSE - C,12,10,2,0
5,Data Science & GenAI - 3nd Yr - CSE - C,12,11,1,0
6,Data Science & GenAI - 3nd Yr - CSE - C,12,11,1,0
7,Data Science & GenAI - 3nd Yr - CSE - C,12,12,0,0
8,Data Science & GenAI - 3nd Yr - CSE - C,12,9,3,0
9,Data Science & GenAI - 3nd Yr - CSE - C,12,3,9,0
10,Data Science & GenAI - 3nd Yr - CSE - C,12,10,2,0
11,Data Science & GenAI - 3nd Yr - CSE - C,12,8,4,0
12,Data Science & GenAI - 3nd Yr - CSE - C,12,11,1,0
13,Data Science & GenAI - 3nd Yr - CSE - C,12,9,3,0
14,Data Science & GenAI - 3nd Yr - CSE - C,12,11,1,0

In [16]:
"""Q8. Find all students whose Consecutive Absences is greater than or equal to 5. Display their name, status, and last present date."""
#-----------------------------Write Solution Code-----------------------------
df[df['consecutive_absences']>=5][['student_name','status','last_present_date']]

          student_name    status last_present_date
20  SHREEHARI SHENOY R  Critical               NaT
43             SURAJ R  Critical               NaT
45    SUSHAN S POOJARY  Critical        2026-09-04
53     UTHSAV N SHETTY  Critical        2026-09-09
62   SANATH S DEVADIGA  Critical        2026-09-04
63            SUSHANTH  Critical        2026-09-04
64            YASHVITH  Critical               NaT

### Section 3: Grouping & Aggregation

In [18]:
"""Q9. Group the data by Status and compute: 
a) Count of students 
b) Average attendance %  
c) Maximum consecutive absences"""
#-----------------------------Write Solution Code-----------------------------
df.groupby('status').agg({'student_name':'count','attendance_pct':'mean','consecutive_absences':'max'})

          student_name  attendance_pct  consecutive_absences
status
Critical            21        0.383333                    12
Safe                20        0.944000                     1
Warning             24        0.800000                     1

In [22]:
"""Q10. Create a new column Attendance Category:
≥ 90% → "Excellent"
75-89% → "Good"
60-74% → "Average"
< 60% → "Poor"
Then use groupby() to count students in each category."""
#-----------------------------Write Solution Code-----------------------------
df.loc[df['attendance_pct']>=90,'Attendance Category']='Excellent'
df.loc[df['attendance_pct']>=75&(df['attendance_pct']<=89),'Attendance Category']='Good'
df.loc[df['attendance_pct']>=60&(df['attendance_pct']<=74),'Attendance Category']='Average'
df.loc[df['attendance_pct']<60,'Attendance Category']='Poor'
df.groupby('Attendance Category').size()

Attendance Category
Poor    65
dtype: int64

In [23]:
"""Q11. Calculate the total number of classes conducted (sum of Total Classes) and the total present/absent counts across all students using .agg()."""
#-----------------------------Write Solution Code-----------------------------
df[['total_classes','present','absent']].agg('sum')

total_classes    779
present          553
absent           226
dtype: int64

In [24]:
"""Q12. Group by Status and use .agg() to find:
a)min, max, and mean of Present
b)sum of Absent"""
#-----------------------------Write Solution Code-----------------------------
df.groupby('status').agg({'present':['min','max','mean'],'absent':'sum'})

         present                absent
             min max       mean    sum
status
Critical       0   8   4.571429    155
Safe          11  12  11.300000     14
Warning        9  10   9.625000     57

### Section 4: Feature Engineering & Transformation

In [25]:
"""Q13. Create a new column Risk Score using the formula:
Risk Score = (Absent * 0.4) + (Consecutive Absences * 0.6)
Display the top 10 students with the highest risk score."""
#-----------------------------Write Solution Code-----------------------------
df['Risk Score']=(df['absent']*0.4)+(df['consecutive_absences']*0.6)
df.nlargest(10,'Risk Score')

,roll_no,student_name,subject,total_classes,present,absent,excused,attendance_pct,status,classes_needed_75pct,last_present_date,consecutive_absences,Attendance Category,Risk Score
20,4MW24CS144,SHREEHARI SHENOY R,Data Science & GenAI - 3nd Yr - CSE - C,12,0,12,0,0.00,Critical,36 more,NaT,12,Poor,12.0
43,4MW24CS167,SURAJ R,Data Science & GenAI - 3nd Yr - CSE - C,12,0,12,0,0.00,Critical,36 more,NaT,12,Poor,12.0
64,4MW25CS409,YASHVITH,Data Science & GenAI - 3nd Yr - CSE - C,12,0,12,0,0.00,Critical,36 more,NaT,12,Poor,12.0
45,4MW24CS169,SUSHAN S POOJARY,Data Science & GenAI - 3nd Yr - CSE - C,12,1,11,0,0.08,Critical,32 more,2026-09-04,10,Poor,10.4
62,4MW25CS407,SANATH S DEVADIGA,Data Science & GenAI - 3nd Yr - CSE - C,12,1,11,0,0.08,Critical,32 more,2026-09-04,10,Poor,10.4
63,4MW25CS408,SUSHANTH,Data Science & GenAI - 3nd Yr - CSE - C,12,1,11,0,0.08,Critical,32 more,2026-09-04,10,Poor,10.4
53,4MW24CS177,UTHSAV N SHETTY,Data Science & GenAI - 3nd Yr - CSE - C,12,2,10,0,0.17,Critical,28 more,2026-09-09,9,Poor,9.4
2,4MW24CS125,SAMEER ACHARYA,Data Science & GenAI - 3nd Yr - CSE - C,12,2,10,0,0.17,Critical,28 more,2026-09-25,3,Poor,5.8
9,4MW24CS133,SARGAM,Data Science & GenAI - 3nd Yr - CSE - C,12,3,9,0,0.25,Critical,24 more,2026-09-25,3,Poor,5.4
22,4MW24CS146,SHREESHESHA G A,Data Science & GenAI - 3nd Yr - CSE - C,12,4,8,0,0.33,Critical,20 more,2026-10-07,1,Poor,3.8

In [30]:
"""Q14. Add a column Classes Needed (Numeric) by extracting the numeric value from the Classes Needed (75%) column (e.g., "5 more" → 5, "✓ Met" → 0)."""
#-----------------------------Write Solution Code-----------------------------
df['Classes Needed(Numeric)']=df['classes_needed_75pct'].str.extract(r'(\d+)')[0].fillna(0).astype(int)
df

,roll_no,student_name,subject,total_classes,present,absent,excused,attendance_pct,status,classes_needed_75pct,last_present_date,consecutive_absences,Attendance Category,Risk Score,Classes Needed(Numeric)
0,4MW24CS123,SAKSHI SHETTY,Data Science & GenAI - 3nd Yr - CSE - C,12,12,0,0,1.00,Safe,✓ Met,2026-10-09,0,Poor,0.0,0
1,4MW24CS124,SAMEEKSHA BEKAL,Data Science & GenAI - 3nd Yr - CSE - C,12,11,1,0,0.92,Safe,✓ Met,2026-10-07,1,Poor,1.0,0
2,4MW24CS125,SAMEER ACHARYA,Data Science & GenAI - 3nd Yr - CSE - C,12,2,10,0,0.17,Critical,28 more,2026-09-25,3,Poor,5.8,28
3,4MW24CS126,SAMHITA S RAO,Data Science & GenAI - 3nd Yr - CSE - C,12,9,3,0,0.75,Warning,✓ Met,2026-10-09,0,Poor,1.2,0
4,4MW24CS127,SAMIKSHA,Data Science & GenAI - 3nd Yr - CSE - C,12,10,2,0,0.83,Warning,✓ Met,2026-10-07,1,Poor,1.4,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60,4MW24CS900,RIYA SHETTY,Data Science & GenAI - 3nd Yr - CSE - C,12,7,5,0,0.58,Critical,8 more,2026-10-09,0,Poor,2.0,8
61,4MW25CS401,ANIRUDH,Data Science & GenAI - 3nd Yr - CSE - C,12,8,4,0,0.67,Critical,4 more,2026-10-07,1,Poor,2.2,4
62,4MW25CS407,SANATH S DEVADIGA,Data Science & GenAI - 3nd Yr - CSE - C,12,1,11,0,0.08,Critical,32 more,2026-09-04,10,Poor,10.4,32
63,4MW25CS408,SUSHANTH,Data Science & GenAI - 3nd Yr - CSE - C,12,1,11,0,0.08,Critical,32 more,2026-09-04,10,Poor,10.4,32
64,4MW25CS409,YASHVITH,Data Science & GenAI - 3nd Yr - CSE - C,12,0,12,0,0.00,Critical,36 more,NaT,12,Poor,12.0,36

In [32]:
"""Q15. Using apply() with a lambda function, create a column Attendance Flag that returns:
a)"Defaulter" if attendance < 75%
b)"Safe" otherwise """
#-----------------------------Write Solution Code-----------------------------
df['Attendance Flag']=df['attendance_pct'].apply(lambda x:"Defaulter"if x<75 else"Safe")
df

,roll_no,student_name,subject,total_classes,present,absent,excused,attendance_pct,status,classes_needed_75pct,last_present_date,consecutive_absences,Attendance Category,Risk Score,Classes Needed(Numeric),Attendance Flag
0,4MW24CS123,SAKSHI SHETTY,Data Science & GenAI - 3nd Yr - CSE - C,12,12,0,0,1.00,Safe,✓ Met,2026-10-09,0,Poor,0.0,0,Defaulter
1,4MW24CS124,SAMEEKSHA BEKAL,Data Science & GenAI - 3nd Yr - CSE - C,12,11,1,0,0.92,Safe,✓ Met,2026-10-07,1,Poor,1.0,0,Defaulter
2,4MW24CS125,SAMEER ACHARYA,Data Science & GenAI - 3nd Yr - CSE - C,12,2,10,0,0.17,Critical,28 more,2026-09-25,3,Poor,5.8,28,Defaulter
3,4MW24CS126,SAMHITA S RAO,Data Science & GenAI - 3nd Yr - CSE - C,12,9,3,0,0.75,Warning,✓ Met,2026-10-09,0,Poor,1.2,0,Defaulter
4,4MW24CS127,SAMIKSHA,Data Science & GenAI - 3nd Yr - CSE - C,12,10,2,0,0.83,Warning,✓ Met,2026-10-07,1,Poor,1.4,0,Defaulter
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60,4MW24CS900,RIYA SHETTY,Data Science & GenAI - 3nd Yr - CSE - C,12,7,5,0,0.58,Critical,8 more,2026-10-09,0,Poor,2.0,8,Defaulter
61,4MW25CS401,ANIRUDH,Data Science & GenAI - 3nd Yr - CSE - C,12,8,4,0,0.67,Critical,4 more,2026-10-07,1,Poor,2.2,4,Defaulter
62,4MW25CS407,SANATH S DEVADIGA,Data Science & GenAI - 3nd Yr - CSE - C,12,1,11,0,0.08,Critical,32 more,2026-09-04,10,Poor,10.4,32,Defaulter
63,4MW25CS408,SUSHANTH,Data Science & GenAI - 3nd Yr - CSE - C,12,1,11,0,0.08,Critical,32 more,2026-09-04,10,Poor,10.4,32,Defaulter
64,4MW25CS409,YASHVITH,Data Science & GenAI - 3nd Yr - CSE - C,12,0,12,0,0.00,Critical,36 more,NaT,12,Poor,12.0,36,Defaulter

In [33]:
"""Q16. Use pd.cut() to bin students into attendance ranges: [0-50, 50-75, 75-90, 90-100] and label them as ["Critical", "Warning", "Good", "Excellent"]."""
#-----------------------------Write Solution Code-----------------------------
df['Attendance Range']=pd.cut(df['attendance_pct'],bins=[0,50,75,90,100],labels=["Critical","Warning","Good","Excellent"])

### Section 5: Advanced Analysis

In [34]:
"""Q17. Using pivot_table(), create a summary showing the count of students by Status and Attendance Category (created in Q10)."""
#-----------------------------Write Solution Code-----------------------------
df.pivot_table(index='status',columns='Attendance Category',values='student_name',aggfunc='count')

Attendance Category  Poor
status
Critical               21
Safe                   20
Warning                24

In [35]:
"""Q18. Identify duplicate student names (e.g., "ANANYA", "DISHA") and display all rows where the base name repeats. Use string manipulation to extract the base name."""
#-----------------------------Write Solution Code-----------------------------
df['Base_Name']=df['student_name'].str.split().str[0]
df[df['Base_Name'].duplicated(keep=False)]

,roll_no,student_name,subject,total_classes,present,absent,excused,attendance_pct,status,classes_needed_75pct,last_present_date,consecutive_absences,Attendance Category,Risk Score,Classes Needed(Numeric),Attendance Flag,Attendance Range,Base_Name
23,4MW24CS147,SHREYA (JAYANTH ),Data Science & GenAI - 3nd Yr - CSE - C,12,11,1,0,0.92,Safe,✓ Met,2026-10-09,0,Poor,0.4,0,Defaulter,Critical,SHREYA
26,4MW24CS150,SHREYA (VIJAYENDRA),Data Science & GenAI - 3nd Yr - CSE - C,12,11,1,0,0.92,Safe,✓ Met,2026-10-09,0,Poor,0.4,0,Defaulter,Critical,SHREYA
27,4MW24CS151,SHREYA K,Data Science & GenAI - 3nd Yr - CSE - C,12,10,2,0,0.83,Warning,✓ Met,2026-10-09,0,Poor,0.8,0,Defaulter,Critical,SHREYA
28,4MW24CS152,SHREYA PRABHU,Data Science & GenAI - 3nd Yr - CSE - C,12,11,1,0,0.92,Safe,✓ Met,2026-10-09,0,Poor,0.4,0,Defaulter,Critical,SHREYA
29,4MW24CS153,SHREYA SHETTY,Data Science & GenAI - 3nd Yr - CSE - C,12,11,1,0,0.92,Safe,✓ Met,2026-10-09,0,Poor,0.4,0,Defaulter,Critical,SHREYA
46,4MW24CS170,SUSHANTH (SEETHARAMA ACHAR),Data Science & GenAI - 3nd Yr - CSE - C,12,8,4,0,0.67,Critical,4 more,2026-10-09,0,Poor,1.6,4,Defaulter,Critical,SUSHANTH
63,4MW25CS408,SUSHANTH,Data Science & GenAI - 3nd Yr - CSE - C,12,1,11,0,0.08,Critical,32 more,2026-09-04,10,Poor,10.4,32,Defaulter,Critical,SUSHANTH

In [36]:
""""Q19. Merge this dataset with a hypothetical Student_Details DataFrame containing Roll No, Branch, and Semester. Perform an inner join and display the merged result."""
#-----------------------------Write Solution Code-----------------------------
merged_df=pd.merge(df,Student_Details,on='roll_no',how='inner')
display(merged_df)

NameError: name 'Student_Details' is not defined

In [ ]:
"""Q20. Export the following to separate CSV files:
(a) All "Critical" students
(b) Summary statistics grouped by Status
(c) Top 10 students by Risk Score"""
#-----------------------------Write Solution Code-----------------------------